# Generated by Django 5.1.3 on 2024-11-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
