# Generated by Django 5.1.3 on 2024-11-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mission_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
